### PR TITLE
Fixed sandbox compatibility

### PR DESCRIPTION
**Pull request by davidsd**

### CODE REVIEW

**Comment by ekmett** [comment]
This reminds me. I need to rip out the entire embedding of MPFR in this project going forward. (In 7.10+ we use system GMP without a custom collector.) Are you using this with GHC 7.10?

**Comment by davidsd** [comment]
I'm currently using 7.8.3. Looking forward to being able to use 7.10, but I'm still waiting on several (other) packages.

**Comment by ekmett** [comment]
Next time I do a major release, it'll probably be a complete lobotomy of this package, as it lets me shed the whole internal copy of `mpfr`, etc.

I'll see if I can do a point release with these changes quickly for you though.

**Comment by davidsd** [comment]
Thanks!

**Pull request merged**
